### ISSUE TITLE
Integration: Decubing Managed WCAG?

### ISSUE THREAD

**Issue by bbertucc** [joinedupack/Roadmap#20]
Curious if we want to integrate with Decubing's new product ("Managed WCAG")? This might be a good test of brand/accessibility management before we invest in doing it ourself?

**Comment by nathansmonk** [comment]
Do you have any documentation/sales materials on it that I can review?

**Comment by bbertucc** [comment]
We are signing a deal with our client that guarantees WCAG 2.0 accessibility.

**Comment by bbertucc** [comment]
Killing this. Decubing has no future. Edupack is the future.
